#pragma once

// CForceCompensatePage 对话框

class CForceCompensatePage : public CPropertyPage
{
	DECLARE_DYNAMIC(CForceCompensatePage)
public:
	CForceCompensatePage();
	virtual ~CForceCompensatePage();
// 对话框数据
	enum { IDD = IDD_FORCE_COMPENSATE };
protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV 支持
	DECLARE_MESSAGE_MAP()
public:
	virtual BOOL OnSetActive();
	virtual BOOL OnInitDialog();
	afx_msg HBRUSH OnCtlColor(CDC* pDC, CWnd* pWnd, UINT nCtlColor);
	afx_msg void OnDestroy();
	afx_msg void OnMouseMove(UINT nFlags, CPoint point);
	afx_msg BOOL OnMouseWheel(UINT nFlags, short zDelta, CPoint pt);
	afx_msg void OnVScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar);
	afx_msg void OnEnSetfocusEditForce0();
	afx_msg void OnEnSetfocusEditForce1();
	afx_msg void OnEnSetfocusEditForce2();
	afx_msg void OnEnSetfocusEditForce3();
	afx_msg void OnEnSetfocusEditForce4();
	afx_msg void OnEnSetfocusEditForce5();
	afx_msg void OnEnSetfocusEditForce6();
	afx_msg void OnEnSetfocusEditForce7();
	afx_msg void OnEnSetfocusEditForce8();
	afx_msg void OnEnSetfocusEditForce9();
	afx_msg void OnEnSetfocusEditForce10();
	afx_msg void OnEnSetfocusEditForce11();
	afx_msg void OnEnSetfocusEditForce12();
	afx_msg void OnEnSetfocusEditForce13();
	afx_msg void OnEnSetfocusEditForce14();
	afx_msg void OnEnSetfocusEditForce15();
	afx_msg void OnEnSetfocusEditForce16();
	afx_msg void OnEnSetfocusEditForce17();
	afx_msg void OnEnSetfocusEditForce18();
	afx_msg void OnEnSetfocusEditForce19();
	afx_msg void OnEnSetfocusEditForce20();
	afx_msg void OnEnSetfocusEditForce21();
	afx_msg void OnEnSetfocusEditForce22();
	afx_msg void OnEnSetfocusEditForce23();
	afx_msg void OnEnSetfocusEditForce24();
	afx_msg void OnEnSetfocusEditForce25();
	afx_msg void OnEnSetfocusEditForce29();
	afx_msg void OnEnSetfocusEditForce28();
	afx_msg void OnEnSetfocusEditForce27();
	afx_msg void OnEnSetfocusEditForce26();
	afx_msg void OnEnSetfocusEditHme1Ido();
	afx_msg void OnEnSetfocusEditHme1Id1();
	afx_msg void OnEnSetfocusEditHme1Id2();
	afx_msg void OnEnSetfocusEditHme1Id3();
	afx_msg void OnEnSetfocusEditHme1Id4();
	afx_msg void OnEnSetfocusEditHme1Id5();
	afx_msg void OnEnSetfocusEditHme1Id6();
	afx_msg void OnEnSetfocusEditHme1Id7();
	afx_msg void OnEnSetfocusEditHme1Id8();
	afx_msg void OnEnSetfocusEditHme1Id9();
	afx_msg void OnEnSetfocusEditHme1Id10();
	afx_msg void OnEnSetfocusEditHme1Id11();
	afx_msg void OnEnSetfocusEditHme1Id12();
	afx_msg void OnEnSetfocusEditHme1Id13();
	afx_msg void OnEnSetfocusEditHme1Id14();
	afx_msg void OnEnSetfocusEditHme1Id15();
	afx_msg void OnEnSetfocusEditHme1Id16();
	afx_msg void OnEnSetfocusEditHme1Id17();
	afx_msg void OnEnSetfocusEditHme1Id18();
	afx_msg void OnEnSetfocusEditHme1Id19();
	afx_msg void OnEnSetfocusEditHme1Id20();
	afx_msg void OnEnSetfocusEditHme1Id21();
	afx_msg void OnEnSetfocusEditHme1Id22();
	afx_msg void OnEnSetfocusEditHme1Id23();
	afx_msg void OnEnSetfocusEditHme1Id24();
	afx_msg void OnEnSetfocusEditHme1Id25();
	afx_msg void OnEnSetfocusEditHme1Id26();
	afx_msg void OnEnSetfocusEditHme1Id27();
	afx_msg void OnEnSetfocusEditHme1Id28();
	afx_msg void OnEnSetfocusEditHme1Id29();
	afx_msg void OnEnSetfocusEditHme2Ido();
	afx_msg void OnEnSetfocusEditHme2Id1();
	afx_msg void OnEnSetfocusEditHme2Id2();
	afx_msg void OnEnSetfocusEditHme2Id3();
	afx_msg void OnEnSetfocusEditHme2Id4();
	afx_msg void OnEnSetfocusEditHme2Id5();
	afx_msg void OnEnSetfocusEditHme2Id6();
	afx_msg void OnEnSetfocusEditHme2Id7();
	afx_msg void OnEnSetfocusEditHme2Id8();
	afx_msg void OnEnSetfocusEditHme2Id9();
	afx_msg void OnEnSetfocusEditHme2Id10();
	afx_msg void OnEnSetfocusEditHme2Id11();
	afx_msg void OnEnSetfocusEditHme2Id12();
	afx_msg void OnEnSetfocusEditHme2Id13();
	afx_msg void OnEnSetfocusEditHme2Id14();
	afx_msg void OnEnSetfocusEditHme2Id15();
	afx_msg void OnEnSetfocusEditHme2Id16();
	afx_msg void OnEnSetfocusEditHme2Id17();
	afx_msg void OnEnSetfocusEditHme2Id18();
	afx_msg void OnEnSetfocusEditHme2Id19();
	afx_msg void OnEnSetfocusEditHme2Id20();
	afx_msg void OnEnSetfocusEditHme2Id21();
	afx_msg void OnEnSetfocusEditHme2Id22();
	afx_msg void OnEnSetfocusEditHme2Id23();
	afx_msg void OnEnSetfocusEditHme2Id24();
	afx_msg void OnEnSetfocusEditHme2Id25();
	afx_msg void OnEnSetfocusEditHme2Id26();
	afx_msg void OnEnSetfocusEditHme2Id27();
	afx_msg void OnEnSetfocusEditHme2Id28();
	afx_msg void OnEnSetfocusEditHme2Id29();
private:
	void SaveParameter(void);
	void UpdateMenuVariable(void);
public:
	short m_nPageSize;
	short m_nforce0;
	short m_nforce1;
	short m_nforce2;
	short m_nforce3;
	short m_nforce4;
	short m_nforce5;
	short m_nforce6;
	short m_nforce7;
	short m_nforce8;
	short m_nforce9;
	short m_nforce10;
	short m_nforce11;
	short m_nforce12;
	short m_nforce13;
	short m_nforce14;
	short m_nforce15;
	short m_nforce16;
	short m_nforce17;
	short m_nforce18;
	short m_nforce19;
	short m_nforce20;
	short m_nforce21;
	short m_nforce22;
	short m_nforce23;
	short m_nforce24;
	short m_nforce25;
	short m_nforce26;
	short m_nforce27;
	short m_nforce28;
	short m_nforce29;
	short m_nHmeOne0;
	short m_nHmeOne1;
	short m_nHmeOne2;
	short m_nHmeOne3;
	short m_nHmeOne4;
	short m_nHmeOne5;
	short m_nHmeOne6;
	short m_nHmeOne7;
	short m_nHmeOne8;
	short m_nHmeOne9;
	short m_nHmeOne10;
	short m_nHmeOne11;
	short m_nHmeOne12;
	short m_nHmeOne13;
	short m_nHmeOne14;
	short m_nHmeOne15;
	short m_nHmeOne16;
	short m_nHmeOne17;
	short m_nHmeOne18;
	short m_nHmeOne19;
	short m_nHmeOne20;
	short m_nHmeOne21;
	short m_nHmeOne22;
	short m_nHmeOne23;
	short m_nHmeOne24;
	short m_nHmeOne25;
	short m_nHmeOne26;
	short m_nHmeOne27;
	short m_nHmeOne28;
	short m_nHmeOne29;
	short m_nHmeTwo0;
	short m_nHmeTwo1;
	short m_nHmeTwo2;
	short m_nHmeTwo3;
	short m_nHmeTwo4;
	short m_nHmeTwo5;
	short m_nHmeTwo6;
	short m_nHmeTwo7;
	short m_nHmeTwo8;
	short m_nHmeTwo9;
	short m_nHmeTwo10;
	short m_nHmeTwo11;
	short m_nHmeTwo12;
	short m_nHmeTwo13;
	short m_nHmeTwo14;
	short m_nHmeTwo15;
	short m_nHmeTwo16;
	short m_nHmeTwo17;
	short m_nHmeTwo18;
	short m_nHmeTwo19;
	short m_nHmeTwo20;
	short m_nHmeTwo21;
	short m_nHmeTwo22;
	short m_nHmeTwo23;
	short m_nHmeTwo24;
	short m_nHmeTwo25;
	short m_nHmeTwo26;
	short m_nHmeTwo27;
	short m_nHmeTwo28;
	short m_nHmeTwo29;
};
